# Generated by Django 5.1.3 on 2024-11-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Cnic', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Cnic', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcommingClientInvestments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTo', models.DateField()),
                ('dateFrom', models.DateField()),
                ('Amount', models.CharField(max_length=100)),
                ('Profit', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvestmentsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All Client Investment',
                'verbose_name_plural': 'All Client Investments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Reports.upcommingclientinvestments',),
        ),
        migrations.CreateModel(
            name='UpcommingInvestorInvestments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTo', models.DateField()),
                ('dateFrom', models.DateField()),
                ('Amount', models.CharField(max_length=100)),
                ('Profit', models.CharField(max_length=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.investors')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInvestmentsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All Investor Investment',
                'verbose_name_plural': 'All Investor Investments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Reports.upcomminginvestorinvestments',),
        ),
    ]
